// components/Layout.tsx
import type { PropsWithChildren } from 'react'
import styles from './Layout.module.css'

export default function Layout({ children }: PropsWithChildren) {
	return (
		<div className={styles.layout}>
			<nav className={styles.nav}>
				<a rel="logo" className={styles.logo} href="/">
					unremarkable
				</a>
			</nav>
			<main>{children}</main>
		</div>
	)
}

// src/routes/__layout.svelte
<script>
	import '../app.css'
</script>

<nav>
	<h1><a rel="logo" href="/">unremarkable</a></h1>
</nav>
<main>
	<slot />
</main>

<style>
	nav {
		margin-bottom: max(8vh, 4rem);
	}

	[rel="logo"] {
		color: var(--black);
		font-size: 1.25rem;
		font-weight: normal;
		text-decoration: none;
	}
</style>
